command = [
  "sh",
  "-c",
  "buildctl-daemonless.sh build \
     --frontend dockerfile.v0 \
     --local context=images/bitcoind \
     --local dockerfile=images/bitcoind \
     --output type=oci,dest=bitcoind.tar"
]

artifact_path = "bitcoind.tar"

