command = [
  "bash",
  "-c",
  "dockerd-entrypoint.sh & sleep 5 && \
   docker buildx create --use --name slsa && \
   docker buildx build \
     --platform linux/amd64 \
     -t bitcoind:build \
     -f images/bitcoind/Dockerfile \
     images/bitcoind \
     --load && \
   docker save bitcoind:build -o bitcoind.tar"
]

artifact_path = "bitcoind.tar"

