name: SLSA3 Bitcoind Builder

on:
  workflow_call:
    secrets:
      gh_token:
        required: true
    inputs:
      registry:
        required: true
        type: string
      image_name:
        required: true
        type: string
      # github_token:
      #   required: true
      #   type: string

permissions: read-all

jobs:
  slsa-setup:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    outputs:
      slsa-token: ${{ steps.setup.outputs.slsa-token }}
    steps:
      - name: Check secret length
        env:
          SECRET: ${{ secrets.gh_token }}
        run: |
          if [ ${#SECRET} -gt 0 ]; then
            echo "Secret is set (length: ${#SECRET})"
          else
            echo "Secret is empty or missing"
          fi
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SLSA
        id: setup
        uses: slsa-framework/slsa-github-generator/actions/delegator/delegator_generic_slsa3@v2.1.0
        with:
          # slsa-workflow-recipient: "delegator_generic_slsa3.yml"
          slsa-runner-label: "ubuntu-latest"
          slsa-build-action-path: "./.github/actions/builder-callback"
          slsa-workflow-inputs: ${{ toJson(inputs) }}
        secrets:
          secret1: ${{ secrets.gh_token }}

  slsa-run:
    needs: [slsa-setup]
    permissions:
      id-token: write
      contents: write
      packages: write
      actions: read
    uses: slsa-framework/slsa-github-generator/.github/workflows/delegator_generic_slsa3.yml@v2.1.0
    with:
      slsa-token: ${{ needs.slsa-setup.outputs.slsa-token }}
