name: SLSA3 Bitcoind Builder

on:
  workflow_call:
    secrets:
      gh_token:
        required: true
    inputs:
      registry:
        required: true
        type: string
      image_name:
        required: true
        type: string
      # github_token:
      #   required: true
      #   type: string

permissions: read-all

jobs:
  slsa-setup:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    outputs:
      slsa-token: ${{ steps.setup.outputs.slsa-token }}
    steps:
      - name: Check secret length
        env:
          SECRET: ${{ secrets.gh_token }}
        run: |
          if [ ${#SECRET} -gt 0 ]; then
            echo "Secret is set (length: ${#SECRET})"
          else
            echo "Secret is empty or missing"
          fi
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SLSA
        id: setup
        uses: slsa-framework/slsa-github-generator/actions/delegator/setup-generic@v2.1.0
        with:
          slsa-workflow-recipient: "delegator_generic_slsa3.yml"
          slsa-runner-label: "ubuntu-latest"
          slsa-build-action-path: "./.github/actions/builder-callback"
          slsa-workflow-inputs: ${{ toJson(inputs) }}

  slsa-run:
    needs: [slsa-setup]
    permissions:
      id-token: write
      contents: write
      packages: write
      actions: read
    uses: slsa-framework/slsa-github-generator/.github/workflows/delegator_generic_slsa3.yml@v2.1.0
    with:
      slsa-token: ${{ needs.slsa-setup.outputs.slsa-token }}
    secrets:
      secret1: ${{ secrets.gh_token }}

  sign-and-verify:
    needs: slsa-run
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - name: Install cosign
        if: ${{ github.event_name != 'pull_request' }}
        uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad
        with:
          cosign-release: "v2.5.3"

      - name: Sign image
        shell: bash
        env:
          TAG: ${{ fromJSON(needs.slsa-run.outputs.build-artifacts-outputs).image }}
          DIGEST: ${{ fromJSON(needs.slsa-run.outputs.build-artifacts-outputs).digest }}
        run: |
          echo "$TAG" | xargs -I {} cosign sign --yes {}@${DIGEST}

      - name: Verify image
        shell: bash
        env:
          TAG: ${{ fromJSON(needs.slsa-run.outputs.build-artifacts-outputs).image }}
          DIGEST: ${{ fromJSON(needs.slsa-run.outputs.build-artifacts-outputs).digest }}
        run: |
          echo "$TAG" | xargs -I {} cosign verify \
            --certificate-identity="https://github.com/${{ github.repository }}/.github/workflows/release.yml@${{ github.ref }}" \
            --certificate-oidc-issuer="https://token.actions.githubusercontent.com" \
            "{}@${DIGEST}"
