name: Release bitcoind image

on:
  push:
    branches: ["feat/byob-slsa-wrapper"]
  #   tags: ["*"]
  #   paths: ["images/bitcoind/**"]
  # pull_request:
  #   branches: ["main"]
  #   paths: ["images/bitcoind/**"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/bitcoind

permissions:
  contents: read
  id-token: write
  packages: write
  actions: read

jobs:
  slsa-setup:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-${{ inputs.ubuntu_version }}
    outputs:
      slsa-token: ${{ steps.setup.outputs.slsa-token }}
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
        with:
          fetch-depth: 0

      - name: Setup SLSA
        id: setup
        uses: slsa-framework/slsa-github-generator/actions/delegator/setup-generic@v2.1.0
        with:
          slsa-workflow-recipient: "delegator_generic_slsa3.yml"
          slsa-runner-label: "ubuntu-latest"
          slsa-build-action-path: "./.github/actions/build-callback"
          # slsa-workflow-inputs: ${{ toJson(inputs) }}

  slsa-run:
    needs: [slsa-setup]
    permissions:
      id-token: write
      contents: write
      packages: write
      actions: read
    uses: slsa-framework/slsa-github-generator/.github/workflows/delegator_generic_slsa3.yml@v2.1.0
    with:
      slsa-token: ${{ needs.slsa-setup.outputs.slsa-token }}
