name: Release bitcoind image

on:
  push:
    branches: ["*"]

jobs:
  release:
    uses: ./.github/workflows/builder_bitcoind_slsa3.yml
    with:
      registry: ghcr.io
      image_name: ${{ github.repository }}/bitcoind
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
